# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JobMonitor.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JobMonitor(object):
    def setupUi(self, JobMonitor):
        JobMonitor.setObjectName("JobMonitor")
        JobMonitor.resize(803, 583)
        font = QtGui.QFont()
        font.setPointSize(12)
        JobMonitor.setFont(font)
        self.centralwidget = QtWidgets.QWidget(JobMonitor)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.jobName = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.jobName.setFont(font)
        self.jobName.setObjectName("jobName")
        self.horizontalLayout.addWidget(self.jobName)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.staTab = QtWidgets.QWidget()
        self.staTab.setObjectName("staTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.staTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.statusFileText = QtWidgets.QTextEdit(self.staTab)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.statusFileText.setFont(font)
        self.statusFileText.setReadOnly(True)
        self.statusFileText.setObjectName("statusFileText")
        self.verticalLayout.addWidget(self.statusFileText)
        self.tabWidget.addTab(self.staTab, "")
        self.msgTab = QtWidgets.QWidget()
        self.msgTab.setObjectName("msgTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.msgTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.messageFileText = QtWidgets.QPlainTextEdit(self.msgTab)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.messageFileText.setFont(font)
        self.messageFileText.setReadOnly(True)
        self.messageFileText.setObjectName("messageFileText")
        self.verticalLayout_4.addWidget(self.messageFileText)
        self.tabWidget.addTab(self.msgTab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        JobMonitor.setCentralWidget(self.centralwidget)
        self.actionFindText = QtWidgets.QAction(JobMonitor)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.actionFindText.setFont(font)
        self.actionFindText.setObjectName("actionFindText")

        self.retranslateUi(JobMonitor)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(JobMonitor)

    def retranslateUi(self, JobMonitor):
        _translate = QtCore.QCoreApplication.translate
        JobMonitor.setWindowTitle(_translate("JobMonitor", "Abaqus Job Monitor"))
        self.label.setText(_translate("JobMonitor", "Job:"))
        self.jobName.setText(_translate("JobMonitor", "Job-1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.staTab), _translate("JobMonitor", "Status File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.msgTab), _translate("JobMonitor", "Message File"))
        self.actionFindText.setText(_translate("JobMonitor", "Find Text"))
        self.actionFindText.setToolTip(_translate("JobMonitor", "Find Text"))
        self.actionFindText.setShortcut(_translate("JobMonitor", "Ctrl+F"))
