package:
  name: pyabaqus
  version: 2020.1

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True # [py<39]

source:
  git_url: https://github.com/haiiliin/pyabaqus.git
  git_rev: "2020.1"

requirements:
  build:
    - python
  run:
    - python

test:
  import:
    - abaqus
    - mesh
    - abaqusConstants
about:
  summary: Type hints for Abaqus/Python scripting
  home: https://github.com/haiiliin/pyabaqus
  license: MIT
# conda build pyabaqus -c default -c deliangus
