# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Environment.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Environment(object):
    def setupUi(self, Environment):
        Environment.setObjectName("Environment")
        Environment.resize(308, 99)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        Environment.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Environment)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Environment)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.abaqusCommand = QtWidgets.QLineEdit(Environment)
        self.abaqusCommand.setObjectName("abaqusCommand")
        self.horizontalLayout_2.addWidget(self.abaqusCommand)
        self.browse = QtWidgets.QToolButton(Environment)
        self.browse.setMinimumSize(QtCore.QSize(0, 0))
        self.browse.setObjectName("browse")
        self.horizontalLayout_2.addWidget(self.browse)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Environment)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Environment)
        self.buttonBox.rejected.connect(Environment.reject) # type: ignore
        self.buttonBox.accepted.connect(Environment.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Environment)

    def retranslateUi(self, Environment):
        _translate = QtCore.QCoreApplication.translate
        Environment.setWindowTitle(_translate("Environment", "Select Abaqus Command"))
        self.label.setText(_translate("Environment", "Abaqus Command"))
        self.browse.setText(_translate("Environment", "Browse"))
