# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TextFinder.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TextFinder(object):
    def setupUi(self, TextFinder):
        TextFinder.setObjectName("TextFinder")
        TextFinder.resize(286, 90)
        self.verticalLayout = QtWidgets.QVBoxLayout(TextFinder)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textToFind = QtWidgets.QLineEdit(TextFinder)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.textToFind.setFont(font)
        self.textToFind.setObjectName("textToFind")
        self.verticalLayout.addWidget(self.textToFind)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.previousButton = QtWidgets.QPushButton(TextFinder)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.previousButton.setFont(font)
        self.previousButton.setObjectName("previousButton")
        self.horizontalLayout.addWidget(self.previousButton)
        self.nextButton = QtWidgets.QPushButton(TextFinder)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.nextButton.setFont(font)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout.addWidget(self.nextButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(TextFinder)
        QtCore.QMetaObject.connectSlotsByName(TextFinder)

    def retranslateUi(self, TextFinder):
        _translate = QtCore.QCoreApplication.translate
        TextFinder.setWindowTitle(_translate("TextFinder", "Find Text"))
        self.previousButton.setText(_translate("TextFinder", "Previous"))
        self.nextButton.setText(_translate("TextFinder", "Next"))
